/* eslint-disable @typescript-eslint/naming-convention */
export interface IPhase1Params {
  PHASE_1_FORK_VERSION: Buffer;
  PHASE_1_FORK_SLOT: number;
  INITIAL_ACTIVE_SHARDS: number;

  MAX_SHARDS: number;
  LIGHT_CLIENT_COMMITTEE_SIZE: number;
  GASPRICE_ADJUSTMENT_COEFFICIENT: number;
  MAX_SHARD_BLOCK_SIZE: number;
  TARGET_SHARD_BLOCK_SIZE: number;
  SHARD_BLOCK_OFFSETS: number[];
  MAX_SHARD_BLOCKS_PER_ATTESTATION: number;
  BYTES_PER_CUSTODY_CHUNK: number;
  CUSTODY_RESPONSE_DEPTH: number;
  MAX_GASPRICE: number;
  MIN_GASPRICE: number;
  ONLINE_PERIOD: number;
  LIGHT_CLIENT_COMMITTEE_PERIOD: number;
  MAX_CUSTODY_CHUNK_CHALLENGE_RECORDS: number;
  DOMAIN_SHARD_PROPOSAL: Buffer;
  DOMAIN_SHARD_COMMITTEE: Buffer;
  DOMAIN_LIGHT_CLIENT: Buffer;
  DOMAIN_CUSTODY_BIT_SLASHING: Buffer;
  DOMAIN_LIGHT_SELECTION_PROOF: Buffer;
  DOMAIN_LIGHT_AGGREGATE_AND_PROOF: Buffer;

  RANDAO_PENALTY_EPOCHS: number;
  EARLY_DERIVED_SECRET_PENALTY_MAX_FUTURE_EPOCHS: number;
  EPOCHS_PER_CUSTODY_PERIOD: number;
  CUSTODY_PERIOD_TO_RANDAO_PADDING: number;
  MAX_CHUNK_CHALLENGE_DELAY: number;

  CUSTODY_PRIME: bigint;
  CUSTODY_SECRETS: number;
  BYTES_PER_CUSTODY_ATOM: number;
  CUSTODY_PROBABILITY_EXPONENT: number;
  MAX_CUSTODY_KEY_REVEALS: number;
  MAX_EARLY_DERIVED_SECRET_REVEALS: number;
  MAX_CUSTODY_CHUNK_CHALLENGES: number;
  MAX_CUSTODY_CHUNK_CHALLENGE_RESPONSES: number;
  MAX_CUSTODY_SLASHINGS: number;
  EARLY_DERIVED_SECRET_REVEAL_SLOT_REWARD_MULTIPLE: number;
  MINOR_REWARD_QUOTIENT: number;
}
