/* eslint-disable @typescript-eslint/naming-convention */

export const altairJson = {
  CONFIG_NAME: "minimal",

  SYNC_COMMITTEE_SIZE: 32,
  SYNC_PUBKEYS_PER_AGGREGATE: 16,
  INACTIVITY_SCORE_BIAS: 4,

  EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 8,

  DOMAIN_SYNC_COMMITTEE: "0x07000000",
  DOMAIN_SYNC_COMMITTEE_SELECTION_PROOF: "0x08000000",
  DOMAIN_CONTRIBUTION_AND_PROOF: "0x09000000",

  ALTAIR_FORK_VERSION: "0x01000001",
  ALTAIR_FORK_EPOCH: "0xffffffffffffffff",

  INACTIVITY_PENALTY_QUOTIENT_ALTAIR: 50331648,
  MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR: 64,
  PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR: 2,
};
