---
labels:
  - files:
      - "packages/lodestar/**/*"
    label: "mod1-beaconchain"
  - files:
      - "packages/validator/**/*"
    label: "mod2-validator"
  - files:
      - "packages/light-client/**/*"
    label: "mod3-lightclient"
  - files:
      - "packages/lodestar/src/api/**/*"
      - "packages/api/**/*"
    label: "mod4-api"
  - files:
      - "packages/cli/**/*"
    label: "mod5-cli"
  - files:
      - "packages/beacon-state-transition/**/*"
      - "packages/spec-test-runner/**/*"
      - "packages/spec-test-util/**/*"
    label: "mod6-statetransition"
  - files:
      - "packages/types/**/*"
    label: "mod7-types"
  - files:
      - "packages/params/**/*"
    label: "mod8-params"
  - files:
      - "packages/utils/**/*"
    label: "mod9-utils"
  - files:
      - "packages/config/**/*"
      - "packages/params/**/*"
    label: "moda-config"
  - files:
      - "packages/db/**/*"
    label: "modb-database"
  - files:
      - "packages/fork-choice/**/*"
    label: "modc-forkchoice"
  - files:
      - "packages/spec-test-runner/**/*"
      - "packages/spec-test-util/**/*"
    label: "modd-spectests"
  - files:
      - "packages/lodestar/test/benchmarks/**/*"
    label: "scope4-benchmarks"
  - files:
      - "packages/lodestar/src/network/**/*"
      - "packages/lodestar/src/sync/**/*"
    label: "scope5-networking"
  - files:
      - "packages/lodestar/src/eth1/**/*"
    label: "scopea-eth1"
  - files:
      - .github/**/*
    label: "scopeb-ci"
version: 1
