StateTransition:
  - packages/beacon-state-transition/**/*
  - packages/spec-test-runner/**/*
  - packages/spec-test-util/**/*

CLI:
  - packages/cli/**/*

Types:
  - packages/types/**/*

Config:
  - packages/config/**/*
  - packages/params/**/*

Validator:
  - packages/validator/**/*

Api:
  - packages/lodestar/src/api/**/*

Network:
  - packages/lodestar/src/network/**/*
  - packages/lodestar/src/sync/**/*

Eth1:
  - packages/lodestar/src/eth1/**/*

Benchmarks:
  - packages/lodestar/test/benchmarks/**/*

CI:
  - .github/**/*
