version: 1
labels:
- label: "mod1-beaconchain"
  files:
  - packages/lodestar/**/*
- label: "mod2-validator"
  files:
  - packages/validator/**/*
- label: "mod3-lightclient"
  files:
  - packages/light-client/**/*
- label: "mod4-api"
  files:
  - packages/lodestar/src/api/**/*
  - packages/api/**/*
- label: "mod5-cli"
  files:
  - packages/cli/**/*
- label: "mod6-statetransition"
  files:
  - packages/beacon-state-transition/**/*
  - packages/spec-test-runner/**/*
  - packages/spec-test-util/**/*
- label: "mod7-types"
  files:
  - packages/types/**/*
- label: "mod8-params"
  files:
  - packages/params/**/*
- label: "mod9-utils"
  files:
  - packages/utils/**/*
- label: "moda-config"
  files:
  - packages/config/**/*
  - packages/params/**/*
- label: "modb-database"
  files:
  - packages/db/**/*
- label: "modc-forkchoice"
  files:
  - packages/fork-choice/**/*
- label: "modd-spectests"
  files:
  - packages/spec-test-runner/**/*
  - packages/spec-test-util/**/*
- label: "scope4-benchmarks"
  files:
  - packages/lodestar/test/benchmarks/**/*
- label: "scope5-networking"
  files:
  - packages/lodestar/src/network/**/*
  - packages/lodestar/src/sync/**/*
- label: "scopea-eth1"
  files:
  - packages/lodestar/src/eth1/**/*
- label: "scopeb-ci"
  files:
  - .github/**/*
- label: "status3-needsreview"
  mergeable: true
- label: "status9-workinprogress"
  mergeable: false
