---
# Spec
params.PRESET_BASE: minimal
params.ALTAIR_FORK_EPOCH: "0"
params.MERGE_FORK_EPOCH: "1"
params.TERMINAL_TOTAL_DIFFICULTY: 16

# Networking - consensus
network.bootMultiaddrs: /ip4/35.178.114.73/tcp/9000

# Execution engine
eth1.enabled: true
eth1.providerUrls: http://localhost:8545
execution.urls: http://localhost:8545

# Other opts
api.rest.enabled: true
api.rest.host: 0.0.0.0
logFile: beacon.log
logLevelFile: debug
logRotate: true
logMaxFiles: 5
