matrix:
  - name: markdown
    aspell:
      lang: en
      ignore-case: true
    dictionary:
      wordlists:
        - .wordlist.txt
    pipeline:
      - pyspelling.filters.url:
      - pyspelling.filters.markdown:
      - pyspelling.filters.url:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
      - pyspelling.filters.context:
          context_visible_first: true
          delimiters:
          # Ignore possessive endings
          - open: '(?<=\w)''s(?!\w)'
            close: '\b'
          # Ignore multiline content between fences (fences can have 3 or more back ticks)
          # ```
          # content
          # ```
          # - open: '^(?P<open>`{3,})$'
            # close: '^(?P=open)$'
          # Ignore text between inline back ticks
          # - open: '(?P<open>`+)'
            # close: '(?P=open)'
    sources:
      - "docs/**/*.md"
      - "CONTRIBUTING.md"
      - "README.md"
      # - "packages/*/README.md"