matrix:
  - name: markdown
    aspell:
      lang: en
      ignore-case: true
    dictionary:
      wordlists:
        - .wordlist.txt
    pipeline:
      - pyspelling.filters.url:
      - pyspelling.filters.markdown:
      - pyspelling.filters.url:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - "docs/**/*.md"
      - "CONTRIBUTING.md"
      - "README.md"
      # - "packages/*/README.md"