version: "3.4"
services:
  beacon_node:
    build:
      target: development
    image: lodestar:dev
    volumes:
      - ./:/usr/app
      - ../dev/lodestar/node_modules:/usr/app/node_modules

      - ../dev/lodestar/benchmark-utils/node_modules:/usr/app/packages/benchmark-utils/node_modules
      - ../dev/lodestar/benchmark-utils/lib:/usr/app/packages/benchmark-utils/lib

      - ../dev/lodestar/lodestar/node_modules:/usr/app/packages/lodestar/node_modules
      - ../dev/lodestar/lodestar/lib:/usr/app/packages/lodestar/lib

      - ../dev/lodestar/lodestar-beacon-state-transition/node_modules:/usr/app/packages/lodestar-beacon-state-transition/node_modules
      - ../dev/lodestar/lodestar-beacon-state-transition/lib:/usr/app/packages/lodestar-beacon-state-transition/lib

      - ../dev/lodestar/lodestar-cli/node_modules:/usr/app/packages/lodestar-cli/node_modules
      - ../dev/lodestar/lodestar-cli/lib:/usr/app/packages/lodestar-cli/lib

      - ../dev/lodestar/lodestar-config/node_modules:/usr/app/packages/lodestar-config/node_modules
      - ../dev/lodestar/lodestar-config/lib:/usr/app/packages/lodestar-config/lib

      - ../dev/lodestar/lodestar-db/node_modules:/usr/app/packages/lodestar-db/node_modules
      - ../dev/lodestar/lodestar-db/lib:/usr/app/packages/lodestar-db/lib

      - ../dev/lodestar/lodestar-fork-choice/node_modules:/usr/app/packages/lodestar-fork-choice/node_modules
      - ../dev/lodestar/lodestar-fork-choice/lib:/usr/app/packages/lodestar-fork-choice/lib

      - ../dev/lodestar/lodestar-light-client/node_modules:/usr/app/packages/lodestar-light-client/node_modules
      - ../dev/lodestar/lodestar-light-client/lib:/usr/app/packages/lodestar-light-client/lib

      - ../dev/lodestar/lodestar-params/node_modules:/usr/app/packages/lodestar-params/node_modules
      - ../dev/lodestar/lodestar-params/lib:/usr/app/packages/lodestar-params/lib

      - ../dev/lodestar/lodestar-spec-test-util/node_modules:/usr/app/packages/lodestar-spec-test-util/node_modules
      - ../dev/lodestar/lodestar-spec-test-util/lib:/usr/app/packages/lodestar-spec-test-util/lib

      - ../dev/lodestar/lodestar-types/node_modules:/usr/app/packages/lodestar-types/node_modules
      - ../dev/lodestar/lodestar-types/lib:/usr/app/packages/lodestar-types/lib

      - ../dev/lodestar/lodestar-utils/node_modules:/usr/app/packages/lodestar-utils/node_modules
      - ../dev/lodestar/lodestar-utils/lib:/usr/app/packages/lodestar-utils/lib

      - ../dev/lodestar/lodestar-validator/node_modules:/usr/app/packages/lodestar-validator/node_modules
      - ../dev/lodestar/lodestar-validator/lib:/usr/app/packages/lodestar-validator/lib

      - ../dev/lodestar/persistent-ts/node_modules:/usr/app/packages/persistent-ts/node_modules
      - ../dev/lodestar/persistent-ts/lib:/usr/app/packages/persistent-ts/lib

      - ../dev/lodestar/spec-test-runner/node_modules:/usr/app/packages/spec-test-runner/node_modules
      - ../dev/lodestar/spec-test-runner/lib:/usr/app/packages/spec-test-runner/lib




    command: tail -F anything