#!/usr/bin/env sh

# Convenience script to run the lodestar binary from built source
#
# ./lodestar.sh beacon --network mainnet

exec node --trace-deprecation --max-old-space-size=32768 ./packages/cli/bin/lodestar.js "$@"
