#!/usr/bin/env bash

# Convenience script to run the lodestar binary from built source
#
# ./lodestar.sh beacon --network prater

node --trace-deprecation --max-old-space-size=6144 ./packages/cli/bin/lodestar "$@"