site_name: Lodestar Documentation
site_description: Lodestar Documentation - Typescript Ethereum Consensus client
site_url: https://chainsafe.github.io/lodestar

repo_name: chainsafe/lodestar
repo_url: https://github.com/chainsafe/lodestar

# Configuration
theme:
  name: material
  logo: assets/lodestar_icon_300.png
  favicon: assets/round-icon.ico
  palette:
    - scheme: preference
      media: "(prefers-color-scheme: light)"
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  nav_style: dark

plugins:
  - search
  - mermaid2:
      version: 8.6.4
      arguments:
        theme: |
          ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'

markdown_extensions:
  - meta
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      # make exceptions to highlighting of code (for mermaid):
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
extra_css:
  - stylesheets/extras.css

# Socials
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ChainSafe/lodestar
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ChainSafeth
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yjyvFRP
    - icon: fontawesome/brands/medium
      link: https://blog.chainsafe.io

# Customize left navigation menu
nav:
  - Getting Started: index.md
  - Installation:
      - Install from source: install/source.md
      - Install from NPM: install/npm.md
      - Install with Docker: install/docker.md
  - Using Lodestar:
      - Beacon management: usage/beacon-management.md
      - Local testnet: usage/local.md
      - Validator management: usage/validator-management.md
      - Prometheus & Grafana Setup: usage/prometheus-grafana.md
      - MEV Builder Integration: usage/mev-integration.md 
      - Client monitoring: usage/client-monitoring.md
  - Reference:
      - Command line: reference/cli.md
  - Libraries: libraries/index.md
  - Design:
      - Lodestar package structure: design/depgraph.md
  - Contributing: contributing.md
