packages:
  - packages/*

linkWorkspacePackages: true

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "@vekexasia/bigint-buffer2"
  - "@chainsafe/*"
  - "@libp2p/*"
  - "libp2p"

nodeLinker: isolated

catalog:
  "@chainsafe/lodestar-z": "github:chainsafe/lodestar-z#b82750f6c3ec3d57ed63fe31c2f968d4527ce0a5"
  "@vitest/browser": "^4.0.7"
  "@vitest/browser-playwright": "^4.0.7"
  "@vitest/coverage-v8": "^4.0.7"
  vitest: "^4.0.7"

allowBuilds:
  "@chainsafe/lodestar-z": true
  "@parcel/watcher": true
  "@swc/core": true
  aws-sdk: true
  "@vekexasia/bigint-buffer2": true
  classic-level: true
  core-js: true
  cpu-features: true
  electron: true
  esbuild: true
  nx: true
  ssh2: true

overrides:
  dns-over-http-resolver: "^2.1.1"
  elliptic: ">=6.6.1"
  loupe: "^2.3.6"
  nan: "^2.19.0"
