packages:
  - packages/*

catalog:
  '@chainsafe/lodestar-z': github:chainsafe/lodestar-z#bing/blst-mt-verify
  '@vitest/browser': ^4.0.7
  '@vitest/browser-playwright': ^4.0.7
  '@vitest/coverage-v8': ^4.0.7
  vitest: ^4.0.7

linkWorkspacePackages: true

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "@libp2p/*"

nodeLinker: isolated

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - aws-sdk
  - '@vekexasia/bigint-buffer2'
  - classic-level
  - core-js
  - cpu-features
  - electron
  - esbuild
  - nx
  - ssh2

overrides:
  dns-over-http-resolver": ^2.1.1
  elliptic: '>=6.6.1'
  loupe": ^2.3.6
  nan": ^2.19.0
