name: "Setup and build the repo"
description: "A task to reuse setup steps during multiple jobs"
inputs:
  node:
    description: Node version
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node}}
        check-latest: true
        cache: yarn

    - name: Node.js version
      id: node
      shell: bash
      run: echo "v8CppApiVersion=$(node --print "process.versions.modules")" >> $GITHUB_OUTPUT

    - name: Restore build
      uses: actions/cache/restore@v4
      id: cache-build-restore
      with:
        path: |
          node_modules
          packages/*/node_modules
          lib/
          packages/*/lib
          packages/*/.git-data.json
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{ inputs.node }}-${{ github.sha }}

    - name: Install & build
      if: steps.cache-build-restore.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --frozen-lockfile && yarn build

    - name: Build
      if: steps.cache-build-restore.outputs.cache-hit == 'true'
      shell: bash
      run: yarn build

    - name: Check Build
      shell: bash
      run: yarn check-build

    - name: Build bundle
      shell: bash
      run: yarn build:bundle

    - name: Check bundle
      shell: bash
      run: yarn check-bundle

    - name: Cache build artifacts
      uses: actions/cache@master
      with:
        path: |
          node_modules
          packages/*/node_modules
          lib/
          packages/*/lib
          packages/*/.git-data.json
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{ inputs.node }}-${{ github.sha }}
