name: "Setup and build the repo"
description: "A task to reuse setup steps during multiple jobs"
inputs:
  node:
    description: Node version
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{inputs.node}}
        package-manager-cache: false
        check-latest: true

    - name: Node.js version
      id: node
      shell: bash
      run: echo "v8CppApiVersion=$(node --print "process.versions.modules")" >> "$GITHUB_OUTPUT"

    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Get pnpm store path
      id: pnpm-store
      shell: bash
      run: |
        echo "PNPM_STORE_PATH=$(pnpm store path)" >> "$GITHUB_ENV"

    - name: Restore pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{inputs.node}}-pnpm-store-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-pnpm-store-cache-

    - name: Install
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Restore build cache
      uses: actions/cache/restore@v4
      id: cache-build-restore
      with:
        path: |
          lib/
          packages/*/lib
          packages/*/.git-data.json
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{inputs.node}}-build-cache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-node-${{inputs.node}}-build-cache-${{ github.sha }}

    - name: Build
      shell: bash
      run: pnpm build

    - name: Save build cache
      uses: actions/cache@v4
      with:
        path: |
          lib/
          packages/*/lib
          packages/*/.git-data.json
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{inputs.node}}-build-cache-${{ github.sha }}

    - name: Check Build
      shell: bash
      run: pnpm check-build

    - name: Build bundle
      shell: bash
      run: pnpm build:bundle

    - name: Check bundle
      shell: bash
      run: pnpm check-bundle
