{
 "title": "Lodestar",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Node summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Head Slot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "beacon_head_slot" }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "libp2p_peers" }
   ]
  },
  {
   "title": "Head Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_head_slot" }
   ]
  },
  {
   "title": "Current Finalized Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_finalized_epoch" }
   ]
  },
  {
   "title": "Slots / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(beacon_head_slot[2m])" }
   ]
  },
  {
   "title": "Uptime since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds*1000"
    }
   ]
  },
  {
   "title": "Lodestar version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "lodestar_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "NodeJS version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_version_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Peer count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "lodestar_peers_by_direction", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Slots / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_head_slot[$__rate_interval])"
    }
   ]
  },
  {
   "title": "VM Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Space Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nodejs_heap_space_size_used_bytes",
       "legendFormat": "{{space}}"
      }
     ]
    },
    {
     "title": "External Memory Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "nodejs_external_memory_bytes", "legendFormat": "nodejs_external_memory_bytes" }
     ]
    },
    {
     "title": "Process heap bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "process_heap_bytes" }
     ]
    },
    {
     "title": "GC pause time rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(nodejs_gc_pause_seconds_total[$__rate_interval])",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "GC reclaimed bytes (per interval)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(nodejs_gc_reclaimed_bytes_total[$__rate_interval])",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "GC runs (per interval)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nodejs_gc_runs_total[$__rate_interval])",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "Active requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nodejs_active_requests", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "Event Loop Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "nodejs_eventloop_lag_seconds" }
     ]
    },
    {
     "title": "Active Handles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nodejs_active_handles", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "CPU usage % (Lodestar only)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_user_seconds_total[1m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus scrape duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(scrape_duration_seconds[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Lodestar prom-client is down",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "1-up" }
     ]
    }
   ]
  },
  {
   "title": "Peer stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goodbyes received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(lodestar_peer_goodbye_received[$__rate_interval])",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Peer connected event",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(lodestar_peer_connected[$__rate_interval])",
       "legendFormat": "{{direction}}"
      }
     ]
    },
    {
     "title": "Goodbyes sent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(lodestar_peer_goodbye_sent[$__rate_interval])",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Peer disconnected event",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(lodestar_peer_disconnected[$__rate_interval])",
       "legendFormat": "{{direction}}"
      }
     ]
    },
    {
     "title": "Total unique peers connected to",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "lodestar_peers_total_unique_connected",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Peer connect events offset (must be 0-1)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "lodestar_peer_connected - lodestar_peer_disconnected - lodestar_peers_by_direction"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block processor utilization ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(lodestar_block_processor_total_async_time[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mesh Peers per Topic",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lodestar_gossip_mesh_peers_by_type",
       "legendFormat": "{{gossipType}}"
      }
     ]
    },
    {
     "title": "Beacon Attestation Mesh Peers per Subnet",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lodestar_gossip_mesh_peers_by_beacon_attestation_subnet",
       "legendFormat": "{{subnet}}"
      }
     ]
    }
   ]
  }
 ]
}