---

params.PRESET_BASE: minimal # 8 slots per epoch
genesisValidators: 32
startValidators: 0:31
api.rest.enabled: true
api.rest.host: 0.0.0.0
logFile: beacon.log
logLevelFile: debug
logRotate: true
logMaxFiles: 5
params.ALTAIR_FORK_EPOCH: 0
params.MERGE_FORK_EPOCH: 1
params.SECONDS_PER_ETH1_BLOCK: 4
params.TERMINAL_TOTAL_DIFFICULTY: 16
params.SECONDS_PER_SLOT: 4
eth1.enabled: true
eth1.providerUrls: http://localhost:8550
execution.urls: http://localhost:8550

