version: "3.4"
services:
  beacon_node:
    image: chainsafe/lodestar:next
    restart: always
    volumes:
      - beacon_node:/data
      - logs:/logs
    #ports:
    #  - "9000:9000" # P2P port
    #  - "9596:9596" # REST API port
    command: >
      dev --rootDir /data --genesisValidators 32 --startValidators 0:31
      --api.rest.enabled --api.rest.host 0.0.0.0
      --logFile /logs/beacon.log --logLevelFile debug --logRotate --logMaxFiles 5
      --params.ALTAIR_FORK_EPOCH 0
      --params.MERGE_FORK_EPOCH 0
      --params.TRANSITION_TOTAL_DIFFICULTY 0
      --execution.urls http://localhost:8550
    # NodeJS applications have a default memory limit of 2.5GB.
    # This limit is bit tight for a Prater node, it is recommended to raise the limit
    # since memory may spike during certain network conditions.
    environment:
      NODE_OPTIONS: --max_old_space_size=6144
    network_mode: host

volumes:
  beacon_node:
  logs:
