name: Bug Report
description: Create a bug report to help us improve
title: "[Descriptive title] "
body:
  - type: markdown
    attributes:
      value: |
        **NOTE: General questions should go to the [Discord chat](https://discord.gg/aMxzVcr) instead of the issue tracker.**
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is and steps to reproduce it.
      placeholder: This is what I'm seeing.
    validations:
      required: true   
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: This is what should happen.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error    
    validations:
      required: false
  - type: textarea
    id: attachments
    attributes:
      label: Additional context
      description: If applicable, add screenshots, links or other context about the issue
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Operating system
      description: What type of operating system are you running on?
      multiple: false
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Lodestar version or commit hash
      description: Which version or commit hash of Lodestar are you running? 
      placeholder: v1.8.0 or a4b29cf
    validations:
      required: true
