blank_issues_enabled: true
contact_links:
  - name: Ethereum Bug Bounty
    url: https://ethereum.org/en/bug-bounty/
    about: Earn up to $250,000 USD and a place on the leaderboard by finding protocol, client and Solidity bugs affecting the Ethereum network.
