import {testStatic} from "../../../util/testCases";

testStatic("AggregateAndProof");
testStatic("AttestationData");
testStatic("Attestation");
testStatic("AttesterSlashing");
testStatic("BeaconBlockBody");
testStatic("BeaconBlockHeader");
testStatic("BeaconBlock");
testStatic("BeaconState");
testStatic("Checkpoint");
testStatic("DepositData");
testStatic("Deposit");
testStatic("Eth1Data");
testStatic("Fork");
testStatic("HistoricalBatch");
testStatic("IndexedAttestation");
testStatic("PendingAttestation");
testStatic("ProposerSlashing");
testStatic("Validator");
testStatic("VoluntaryExit");
