import {LodestarError} from "@lodestar/utils";

export enum StateInitializationErrorCode {
  INVALID_CHECKPOINT_SOURCE = "INVALID_CHECKPOINT_SOURCE",
  INCOMPATIBLE_GENESIS = "INCOMPATIBLE_GENESIS",
  CHECKPOINT_ROOT_MISMATCH = "CHECKPOINT_ROOT_MISMATCH",
  CHECKPOINT_EPOCH_MISMATCH = "CHECKPOINT_EPOCH_MISMATCH",
  STALE_CHECKPOINT = "STALE_CHECKPOINT",
  ANCHOR_STATE_FORK_MISMATCH = "ANCHOR_STATE_FORK_MISMATCH",
  GENESIS_ROOT_MISMATCH = "GENESIS_ROOT_MISMATCH",
  MISSING_INITIALIZATION_SOURCE = "MISSING_INITIALIZATION_SOURCE",
}

export class StateInitializationError extends LodestarError<{code: StateInitializationErrorCode}> {}
