import {ValueOf} from "@chainsafe/ssz";
import * as ssz from "./sszTypes.js";

export type ts = {
  AttestationSubnets: ValueOf<typeof ssz.AttestationSubnets>;
  BeaconBlockHeader: ValueOf<typeof ssz.BeaconBlockHeader>;
  BeaconBlockHeaderBigint: ValueOf<typeof ssz.BeaconBlockHeaderBigint>;
  SignedBeaconBlockHeader: ValueOf<typeof ssz.SignedBeaconBlockHeader>;
  SignedBeaconBlockHeaderBigint: ValueOf<typeof ssz.SignedBeaconBlockHeaderBigint>;
  Checkpoint: ValueOf<typeof ssz.Checkpoint>;
  DepositMessage: ValueOf<typeof ssz.DepositMessage>;
  DepositData: ValueOf<typeof ssz.DepositData>;
  DepositEvent: ValueOf<typeof ssz.DepositEvent>;
  Eth1Data: ValueOf<typeof ssz.Eth1Data>;
  Eth1DataOrdered: ValueOf<typeof ssz.Eth1DataOrdered>;
  Eth1Block: ValueOf<typeof ssz.Eth1Block>;
  Fork: ValueOf<typeof ssz.Fork>;
  ForkData: ValueOf<typeof ssz.ForkData>;
  ENRForkID: ValueOf<typeof ssz.ENRForkID>;
  HistoricalBatch: ValueOf<typeof ssz.HistoricalBatch>;
  Validator: ValueOf<typeof ssz.Validator>;
  Validators: ValueOf<typeof ssz.Validators>;
  AttestationData: ValueOf<typeof ssz.AttestationData>;
  AttestationDataBigint: ValueOf<typeof ssz.AttestationDataBigint>;
  IndexedAttestation: ValueOf<typeof ssz.IndexedAttestation>;
  IndexedAttestationBigint: ValueOf<typeof ssz.IndexedAttestationBigint>;
  PendingAttestation: ValueOf<typeof ssz.PendingAttestation>;
  SigningData: ValueOf<typeof ssz.SigningData>;
  Attestation: ValueOf<typeof ssz.Attestation>;
  AttesterSlashing: ValueOf<typeof ssz.AttesterSlashing>;
  Deposit: ValueOf<typeof ssz.Deposit>;
  ProposerSlashing: ValueOf<typeof ssz.ProposerSlashing>;
  VoluntaryExit: ValueOf<typeof ssz.VoluntaryExit>;
  SignedVoluntaryExit: ValueOf<typeof ssz.SignedVoluntaryExit>;
  BeaconBlockBody: ValueOf<typeof ssz.BeaconBlockBody>;
  BeaconBlock: ValueOf<typeof ssz.BeaconBlock>;
  SignedBeaconBlock: ValueOf<typeof ssz.SignedBeaconBlock>;
  BeaconState: ValueOf<typeof ssz.BeaconState>;
  CommitteeAssignment: ValueOf<typeof ssz.CommitteeAssignment>;
  AggregateAndProof: ValueOf<typeof ssz.AggregateAndProof>;
  SignedAggregateAndProof: ValueOf<typeof ssz.SignedAggregateAndProof>;
  Status: ValueOf<typeof ssz.Status>;
  Goodbye: ValueOf<typeof ssz.Goodbye>;
  Ping: ValueOf<typeof ssz.Ping>;
  Metadata: ValueOf<typeof ssz.Metadata>;
  BeaconBlocksByRangeRequest: ValueOf<typeof ssz.BeaconBlocksByRangeRequest>;
  BeaconBlocksByRootRequest: ValueOf<typeof ssz.BeaconBlocksByRootRequest>;
  Genesis: ValueOf<typeof ssz.Genesis>;
};
