colors: true
require: 
  - ts-node/register
  - ./test/mocha-hooks.js
timeout: 600000
# By default, Mocha’s maximum job count is n – 1, where n is the number of CPU cores
# In Github actions the runner has only two cores, so force it to use two
parallel: true
jobs: 2