name: 'Take core dump files'
description: 'List down and upload core dumps as artifacts'
runs:
  using: "composite"
  steps:
    - name: List down all files 
      run: ls -l

    - name: Backup core dump 
      uses: actions/upload-artifact@v2
      with:
        name: core-dump
        path: core.*
