/* eslint-disable @typescript-eslint/naming-convention */

export const lightclientMinimalYaml = {
  CONFIG_NAME: "minimal",

  SYNC_COMMITTEE_SIZE: 64,
  SYNC_COMMITTEE_PUBKEY_AGGREGATES_SIZE: 16,

  EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 256,

  DOMAIN_SYNC_COMMITTEE: "0x07000000",

  LIGHTCLIENT_PATCH_FORK_VERSION: "0x01000000",
  LIGHTCLIENT_PATCH_FORK_SLOT: "99999999999",
};
