export const MAX_ATTESTATION_FIELDS = 8;
export const MAX_INDEXED_ATTESTATION_FIELDS = 8;
export const MAX_EXECUTION_PAYLOAD_FIELDS = 64;
export const MAX_BEACON_BLOCK_BODY_FIELDS = 64;
export const MAX_BEACON_STATE_FIELDS = 128;
