{
 "title": "Libp2p",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_global_stats[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Gossip Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_protocol__meshsub_1_1_0_bytes[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Identify-Push Protocol Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_protocol__ipfs_id_push_1_0_0_bytes[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Identify Protocol Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_protocol__ipfs_id_1_0_0_bytes[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "Connection Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "libp2p_connection_manager_connections",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "libp2p_connection_manager_protocol_streams_total",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Streams Per Connection (90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "libp2p_connection_manager_protocol_streams_per_connection_90th_percentile",
     "legendFormat": "{{protocol}}"
    }
   ]
  }
 ]
}