{
 "title": "Lodestar - state cache + regen",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "stateCache and stateCheckpointCache Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "stateCache total lookups vs hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(lodestar_state_cache_lookups_total[$rate_interval])",
     "legendFormat": "total lookups"
    },
    {
     "expr": "rate(lodestar_state_cache_hits_total[$rate_interval])\n/\nrate(lodestar_state_cache_lookups_total[$rate_interval])",
     "legendFormat": "cache hit ratio"
    }
   ]
  },
  {
   "title": "checkpointStateCache total lookups vs hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(lodestar_cp_state_cache_lookups_total[$rate_interval])",
     "legendFormat": "total lookups"
    },
    {
     "expr": "rate(lodestar_cp_state_cache_hits_total[$rate_interval])\n/\nrate(lodestar_cp_state_cache_lookups_total[$rate_interval])",
     "legendFormat": "cache hit ratio"
    }
   ]
  },
  {
   "title": "stateCache cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "lodestar_state_cache_size{}", "legendFormat": "states" }
   ]
  },
  {
   "title": "checkpointStateCache cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "lodestar_cp_state_cache_size{}", "legendFormat": "states_{{type}}" },
    { "expr": "lodestar_cp_state_epoch_size", "legendFormat": "epochs_{{type}}" }
   ]
  },
  {
   "title": "stateCache add() calls / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "12 * rate(lodestar_state_cache_adds_total{}[6m])",
     "legendFormat": "state cache"
    }
   ]
  },
  {
   "title": "checkpointStateCache add() calls / epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "32 * 12 * rate(lodestar_cp_state_cache_adds_total{}[6m])",
     "legendFormat": "checkpointState cache"
    }
   ]
  },
  {
   "title": "State cache - reads per state entry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "lodestar_state_cache_reads_min", "legendFormat": "min" },
    { "expr": "lodestar_state_cache_reads_avg", "legendFormat": "avg" },
    { "expr": "lodestar_state_cache_reads_max", "legendFormat": "max" }
   ]
  },
  {
   "title": "CP state cache - reads per state entry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "lodestar_cp_state_epoch_reads_min",
     "legendFormat": "min"
    },
    {
     "expr": "lodestar_cp_state_epoch_reads_avg",
     "legendFormat": "avg"
    },
    {
     "expr": "lodestar_cp_state_epoch_reads_max",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "State cache - seconds since last read per state entry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(lodestar_state_cache_seconds_since_last_read_min[$rate_interval])",
     "legendFormat": "min"
    },
    {
     "expr": "avg_over_time(lodestar_state_cache_seconds_since_last_read_avg[$rate_interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(lodestar_state_cache_seconds_since_last_read_max[$rate_interval])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "CP state cache - seconds since last read per state entry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(lodestar_cp_state_epoch_seconds_since_last_read_min[$rate_interval])",
     "legendFormat": "min"
    },
    {
     "expr": "avg_over_time(lodestar_cp_state_epoch_seconds_since_last_read_avg[$rate_interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(lodestar_cp_state_epoch_seconds_since_last_read_max[$rate_interval])",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "n-historical states", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "State persist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_state_serialize_seconds_sum{source=\"persistent_checkpoints_cache_state\"}[$rate_interval])\n/\nrate(lodestar_state_serialize_seconds_count{source=\"persistent_checkpoints_cache_state\"}[$rate_interval])",
     "legendFormat": "serialize_duration"
    },
    {
     "expr": "rate(lodestar_cp_state_cache_state_persist_seconds_from_slot_sum[$rate_interval])\n/\nrate(lodestar_cp_state_cache_state_persist_seconds_from_slot_count[$rate_interval])",
     "legendFormat": "sec_from_slot"
    },
    {
     "expr": "rate(lodestar_cp_state_cache_state_persist_seconds_from_slot_count[$rate_interval]) * 384",
     "legendFormat": "count_per_epoch"
    }
   ]
  },
  {
   "title": "Reload duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_cp_state_cache_state_reload_seconds_sum[$rate_interval])\n/\nrate(lodestar_cp_state_cache_state_reload_seconds_count[$rate_interval])",
     "legendFormat": "reload_duration"
    },
    {
     "expr": "rate(lodestar_cp_state_cache_state_reload_seconds_from_slot_sum[$rate_interval])\n/\nrate(lodestar_cp_state_cache_state_reload_seconds_from_slot_count[$rate_interval])",
     "legendFormat": "sec_from_slot"
    },
    {
     "expr": "rate(lodestar_cp_state_cache_state_reload_db_read_seconds_sum[$rate_interval])\n/\nrate(lodestar_cp_state_cache_state_reload_db_read_seconds_count[$rate_interval])",
     "legendFormat": "db_read_duration"
    },
    {
     "expr": "rate(lodestar_cp_state_cache_state_reload_epoch_diff_sum[$rate_interval])\n/\nrate(lodestar_cp_state_cache_state_reload_epoch_diff_count[$rate_interval])",
     "legendFormat": "epoch_diff"
    },
    {
     "expr": "rate(lodestar_cp_state_cache_state_reload_validators_serialize_seconds_sum[$rate_interval])\n/\nrate(lodestar_cp_state_cache_state_reload_validators_serialize_seconds_count[$rate_interval])",
     "legendFormat": "validators_serialization_duration"
    }
   ]
  },
  {
   "title": "State prune per epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(lodestar_cp_state_cache_state_prune_from_memory_count[$rate_interval]) * 384",
     "legendFormat": "from_memory"
    },
    {
     "expr": "rate(lodestar_cp_state_cache_persisted_state_remove_count[$rate_interval]) * 384",
     "legendFormat": "from_persistent"
    }
   ]
  },
  {
   "title": "Alloc count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(lodestar_cp_state_cache_persisted_state_alloc_count[$rate_interval])",
     "legendFormat": "state_persist"
    },
    {
     "expr": "rate(lodestar_cp_state_cache_state_reload_validators_serialize_alloc_count[$rate_interval])",
     "legendFormat": "state_reload_validator_serialization"
    }
   ]
  },
  {
   "title": "Regen call stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Call rate per slot (grouped by entrypoint)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by (entrypoint) (\n  12 * rate(lodestar_regen_fn_call_total[$rate_interval])\n)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Call rate per slot (grouped by caller)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum by (caller)(\n  12 * rate(lodestar_regen_fn_call_total[$rate_interval])\n)",
     "legendFormat": "{{caller}}"
    }
   ]
  },
  {
   "title": "Regen job avg time (grouped by entrypoint)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (entrypoint) (\n  rate(lodestar_regen_fn_call_duration_sum[$rate_interval])\n)\n/\nsum by (entrypoint) (\n  rate(lodestar_regen_fn_call_duration_count[$rate_interval])\n)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Regen job avg time (grouped by caller)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (caller) (\n  rate(lodestar_regen_fn_call_duration_sum[$rate_interval])\n)\n/\nsum by (caller) (\n  rate(lodestar_regen_fn_call_duration_count[$rate_interval])\n)",
     "legendFormat": "{{caller}}"
    }
   ]
  },
  {
   "title": "Cache miss (grouped by entrypoint)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (entrypoint) (\n  rate(lodestar_regen_fn_queued_total[$rate_interval])\n)\n/\nsum by (entrypoint) (\n  rate(lodestar_regen_fn_call_total[$rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Error rate (grouped by entrypoint)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (entrypoint) (\n  rate(lodestar_regen_fn_errors_total[$rate_interval])\n)\n/\nsum by (entrypoint) (\n  rate(lodestar_regen_fn_call_duration_count[$rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Cache miss (grouped by caller)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (caller) (\n  rate(lodestar_regen_fn_queued_total[$rate_interval])\n)\n/\nsum by (caller) (\n  rate(lodestar_regen_fn_call_total[$rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Error rate (grouped by caller)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (caller) (\n  rate(lodestar_regen_fn_errors_total[$rate_interval])\n)\n/\nsum by (caller) (\n  rate(lodestar_regen_fn_call_duration_count[$rate_interval])\n)"
    }
   ]
  },
  { "title": "Regen - getState", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Get seed state duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_regen_get_state_get_seed_state_seconds_sum[$rate_interval])\n/\nrate(lodestar_regen_get_state_get_seed_state_seconds_count[$rate_interval])",
     "legendFormat": "{{caller}}"
    }
   ]
  },
  {
   "title": "Load blocks duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_regen_get_state_load_blocks_seconds_sum[$rate_interval])\n/\nrate(lodestar_regen_get_state_load_blocks_seconds_count[$rate_interval])",
     "legendFormat": "{{caller}}"
    }
   ]
  },
  {
   "title": "State transition duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_regen_get_state_state_transition_seconds_sum[$rate_interval])\n/\nrate(lodestar_regen_get_state_state_transition_seconds_count[$rate_interval])",
     "legendFormat": "{{caller}}"
    }
   ]
  },
  {
   "title": "Reprocessed block count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "rate(lodestar_regen_get_state_block_count_sum[$rate_interval])\n/\nrate(lodestar_regen_get_state_block_count_count[$rate_interval])",
     "legendFormat": "{{caller}}"
    }
   ]
  },
  {
   "title": "Regen queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Regen queue - Utilization ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_regen_queue_job_time_seconds_sum[32m])",
     "legendFormat": "regen_queue"
    }
   ]
  },
  {
   "title": "Regen queue - Jobs / slot",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "12*rate(lodestar_regen_queue_job_time_seconds_count[$rate_interval])",
     "legendFormat": "regen_queue"
    }
   ]
  },
  {
   "title": "Regen queue - Dropped jobs %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_regen_queue_dropped_jobs_total[$rate_interval])/(rate(lodestar_regen_queue_job_time_seconds_count[$rate_interval])+rate(lodestar_regen_queue_dropped_jobs_total[$rate_interval]))",
     "legendFormat": "regen_queue"
    }
   ]
  },
  {
   "title": "Regen queue - Job time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_regen_queue_job_time_seconds_sum[$rate_interval])/rate(lodestar_regen_queue_job_time_seconds_count[$rate_interval])",
     "legendFormat": "regen_queue"
    }
   ]
  },
  {
   "title": "Regen queue - Job wait time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_regen_queue_job_wait_time_seconds_sum[$rate_interval])/rate(lodestar_regen_queue_job_wait_time_seconds_count[$rate_interval])",
     "legendFormat": "regen_queue"
    }
   ]
  },
  {
   "title": "Regen queue - Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "lodestar_regen_queue_length", "legendFormat": "regen_queue" }
   ]
  }
 ]
}