{
 "title": "Lodestar - BeaconChain",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Process Finalized Checkpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration by Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_process_finalized_checkpoint_seconds_sum[32m])\n/\nrate(lodestar_process_finalized_checkpoint_seconds_count[32m])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "FrequencyStateArchiveStrategy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_process_finalized_checkpoint_frequency_state_archive_seconds_sum[32m])\n/\nrate(lodestar_process_finalized_checkpoint_frequency_state_archive_seconds_count[32m])",
     "legendFormat": "{{step}}"
    }
   ]
  },
  { "title": "Seen Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Block Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "lodestar_seen_block_input_cache_size",
     "legendFormat": "size"
    },
    {
     "expr": "rate(lodestar_seen_block_input_cache_duplicate_block_total[$rate_interval]) * 12",
     "legendFormat": "duplicate_block_{{source}}"
    },
    {
     "expr": "rate(lodestar_seen_block_input_cache_duplicate_blob_total[$rate_interval]) * 12",
     "legendFormat": "duplicate_blob_{{source}}"
    },
    {
     "expr": "rate(lodestar_seen_block_input_cache_duplicate_column_total[$rate_interval]) * 12",
     "legendFormat": "duplicate_columns_{{source}}"
    },
    {
     "expr": "rate(lodestar_seen_block_input_cache_items_created_by_block_total[$rate_interval]) * 12",
     "legendFormat": "created_by_block"
    },
    {
     "expr": "rate(lodestar_seen_block_input_cache_items_created_by_blob_total[$rate_interval]) * 12",
     "legendFormat": "created_by_blob"
    },
    {
     "expr": "rate(lodestar_seen_block_input_cache_items_created_by_column_total[$rate_interval]) * 12",
     "legendFormat": "created_by_column"
    },
    {
     "expr": "lodestar_seen_block_input_cache_serialized_object_refs",
     "legendFormat": "serialized_objects"
    }
   ]
  },
  {
   "title": "Committee Contributions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(lodestar_seen_cache_committee_contributions_super_set_check_total_sum[$rate_interval])\n/\nrate(lodestar_seen_cache_committee_contributions_super_set_check_total_count[$rate_interval])",
     "legendFormat": "super_set_check_total"
    },
    {
     "expr": "rate(lodestar_seen_cache_committee_contributions_is_known_call_total[$rate_interval])",
     "legendFormat": "is_known_calls"
    },
    {
     "expr": "rate(lodestar_seen_cache_committee_contributions_is_known_hit_total[$rate_interval])",
     "legendFormat": "is_known_hits"
    }
   ]
  },
  {
   "title": "Attestation Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "lodestar_seen_cache_attestation_data_slot_total",
     "legendFormat": "total_slot"
    },
    {
     "expr": "lodestar_seen_cache_attestation_data_per_slot_total",
     "legendFormat": "count_per_slot"
    },
    {
     "expr": "rate(lodestar_seen_cache_attestation_data_hit_total[$rate_interval])",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(lodestar_seen_cache_attestation_data_miss_total[$rate_interval])",
     "legendFormat": "miss"
    },
    {
     "expr": "rate(lodestar_seen_cache_attestation_data_reject_total[$rate_interval])",
     "legendFormat": "reject_{{reason}}"
    }
   ]
  },
  {
   "title": "Aggregated Attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(lodestar_seen_cache_aggregated_attestations_super_set_check_total_sum[$rate_interval])\n/\nrate(lodestar_seen_cache_aggregated_attestations_super_set_check_total_count[$rate_interval])",
     "legendFormat": "super_set_check_total"
    },
    {
     "expr": "rate(lodestar_seen_cache_aggregated_attestations_is_known_call_total[$rate_interval])",
     "legendFormat": "is_known_call"
    },
    {
     "expr": "rate(lodestar_seen_cache_aggregated_attestations_is_known_hit_total[$rate_interval])",
     "legendFormat": "is_known_hits"
    }
   ]
  },
  { "title": "Shuffling Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "lodestar_shuffling_cache_size", "legendFormat": "size" }
   ]
  },
  {
   "title": "Insert vs Hit vs Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(lodestar_shuffling_cache_insert_promise_count[32m]) * 384",
     "legendFormat": "insert_promise"
    },
    {
     "expr": "rate(lodestar_shuffling_cache_hit_count[32m]) * 384",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(lodestar_shuffling_cache_miss_count[32m]) * 384",
     "legendFormat": "miss"
    },
    {
     "expr": "rate(lodestar_shuffling_cache_set_multiple_times_count[32m]) * 384",
     "legendFormat": "set_multiple_times"
    },
    {
     "expr": "rate(lodestar_shuffling_cache_promise_not_resolved_count[32m]) * 384",
     "legendFormat": "not_resolved"
    }
   ]
  },
  {
   "title": "Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_shuffling_cache_promise_resolution_time_seconds_sum[32m])\n/\nrate(lodestar_shuffling_cache_promise_resolution_time_seconds_count[32m])",
     "legendFormat": "resolution"
    }
   ]
  },
  { "title": "BufferPool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    { "expr": "lodestar_buffer_pool_length", "legendFormat": "length" }
   ]
  },
  {
   "title": "Hit vs Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rate(lodestar_buffer_pool_hits_total[32m]) * 384",
     "legendFormat": "hit_{{source}}"
    },
    {
     "expr": "rate(lodestar_buffer_pool_misses_total[32m]) * 384",
     "legendFormat": "miss_{{source}}"
    }
   ]
  },
  {
   "title": "Grow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(lodestar_buffer_pool_grows_total[32m]) * 384",
     "legendFormat": "grow"
    }
   ]
  },
  { "title": "Unfinalized Block Writes Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "lodestar_unfinalized_block_writes_queue_length",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "lodestar_unfinalized_block_writes_queue_concurrency",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(lodestar_unfinalized_block_writes_queue_job_time_seconds_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Wait Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "rate(lodestar_unfinalized_block_writes_queue_job_wait_time_seconds_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg Job Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_unfinalized_block_writes_queue_job_time_seconds_sum[$rate_interval])\n/ rate(lodestar_unfinalized_block_writes_queue_job_time_seconds_count[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Job Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_unfinalized_block_writes_queue_job_wait_time_seconds_sum[$rate_interval])\n/ rate(lodestar_unfinalized_block_writes_queue_job_wait_time_seconds_count[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}