{
 "title": "Lodestar - REST API",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "REST API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "REST API response times",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_api_rest_response_time_seconds_sum[$rate_interval])\n/\nrate(lodestar_api_rest_response_time_seconds_count[$rate_interval])",
     "legendFormat": "{{operationId}}"
    }
   ]
  },
  {
   "title": "REST API queries / slot",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "12 * rate(lodestar_api_rest_requests_total[$rate_interval])",
     "legendFormat": "{{operationId}}"
    }
   ]
  },
  {
   "title": "API rest sockets data rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(lodestar_api_rest_sockets_bytes_written_total[$rate_interval])",
     "legendFormat": "written"
    },
    {
     "expr": "-rate(lodestar_api_rest_sockets_bytes_read_total[$rate_interval])",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "api_rest_active_sockets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "lodestar_api_rest_active_sockets_count",
     "legendFormat": "{{operationId}}"
    }
   ]
  },
  {
   "title": "api_rest_errors rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(lodestar_api_rest_errors_total[$rate_interval])",
     "legendFormat": "{{operationId}}"
    }
   ]
  },
  {
   "title": "-",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "legendFormat": "{{operationId}}" }
   ]
  }
 ]
}