{
 "title": "Lodestar",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" },
   { "name": "beacon_job", "label": "Beacon node job name", "query": "${VAR_BEACON_JOB}" },
   { "name": "validator_job", "label": "Validator client job name", "query": "${VAR_VALIDATOR_JOB}" }
  ]
 },
 "panels": [
  {
   "title": "Node summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(time() - lodestar_genesis_time) / 12",
     "legendFormat": "clock slot"
    },
    { "expr": "beacon_head_slot", "legendFormat": "head slot" },
    {
     "expr": "changes(process_start_time_seconds[5m])",
     "legendFormat": "process restart"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(lodestar_peers_by_direction_count)"
    }
   ]
  },
  {
   "title": "Head Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_head_slot" }
   ]
  },
  {
   "title": "Finalized Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_finalized_epoch" }
   ]
  },
  {
   "title": "Validators connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "validator_monitor_validators" }
   ]
  },
  {
   "title": "Custody Group Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_custody_groups", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{job=~\"$beacon_job|beacon\"} [1m])"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_heap_bytes{job=~\"$beacon_job|beacon\"}"
    }
   ]
  },
  {
   "title": "Uptime since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~\"$beacon_job|beacon\"}*1000"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lodestar_sync_status" }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_version{job=~\"$beacon_job|beacon\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Lodestar version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_version{job=~\"$beacon_job|beacon\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{job=~\"$beacon_job|beacon\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lodestar_peers_by_direction_count",
     "legendFormat": "{{direction}}"
    },
    {
     "expr": "lodestar_gossip_peer_score_by_threshold_count{threshold=\"mesh\"}",
     "legendFormat": "with_gossip_mesh_score"
    }
   ]
  },
  {
   "title": "Validators prev epoch miss ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_attester_miss_total[$rate_interval]))\n/\n(\n  sum(rate(validator_monitor_prev_epoch_on_chain_attester_hit_total[$rate_interval]))\n  +\n  sum(rate(validator_monitor_prev_epoch_on_chain_attester_miss_total[$rate_interval]))\n) > 0",
     "legendFormat": "attester"
    },
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total[$rate_interval]))\n/\n(\n  sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_hit_total[$rate_interval]))\n  +\n  sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total[$rate_interval]))\n) > 0",
     "legendFormat": "target"
    },
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total[$rate_interval]))\n/\n(\n  sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_hit_total[$rate_interval]))\n  +\n  sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total[$rate_interval]))\n) > 0",
     "legendFormat": "head"
    }
   ]
  },
  {
   "title": "Mesh peers on core topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(lodestar_gossip_mesh_peers_by_type_count) by (instance)",
     "legendFormat": "core_topics_avg"
    },
    {
     "expr": "avg(lodestar_gossip_mesh_peers_by_beacon_attestation_subnet_count > 0) by (instance)",
     "legendFormat": "attestation_subnets_avg"
    }
   ]
  },
  {
   "title": "balance delta prev epoch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_balance[32m]) / validator_monitor_validators",
     "legendFormat": "balance_delta"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lodestar_peers_by_client_count", "legendFormat": "{{client}}" }
   ]
  },
  {
   "title": "Usage rate (time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_find_head_seconds_sum[$rate_interval])",
     "legendFormat": "fork_choice_find_head"
    },
    {
     "expr": "rate(lodestar_block_processor_queue_job_time_seconds_sum[$rate_interval])",
     "legendFormat": "block_processor"
    },
    {
     "expr": "rate(lodestar_stfn_epoch_transition_seconds_sum[$rate_interval])",
     "legendFormat": "stfn_epoch"
    },
    {
     "expr": "rate(lodestar_stfn_process_block_seconds_sum[$rate_interval])",
     "legendFormat": "stfn_block"
    },
    {
     "expr": "sum(rate(nodejs_gc_duration_seconds_sum{job=~\"$beacon_job|beacon\"} [$rate_interval])) by (instance)",
     "legendFormat": "gc_duration_sum"
    },
    {
     "expr": "sum(rate(nodejs_gc_pause_seconds_total{job=~\"$beacon_job|beacon\"} [$rate_interval])) by (instance)",
     "legendFormat": "gc_pause_sum"
    },
    {
     "expr": "sum(rate(lodestar_bls_thread_pool_time_seconds_sum[$rate_interval])) by (instance)",
     "legendFormat": "bls_thread_pool_sum"
    }
   ]
  },
  {
   "title": "Import head late (> 4 sec) rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_elapsed_time_till_processed_count[$rate_interval])\n- sum without (le) (rate(lodestar_gossip_block_elapsed_time_till_processed_bucket{le=~\"4|4[.]0\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(lodestar_import_block_by_source_total[$rate_interval]) * 12",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Roundtrip request times - I/O lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_reqresp_outgoing_request_roundtrip_time_seconds_sum[$rate_interval])\n/\nrate(beacon_reqresp_outgoing_request_roundtrip_time_seconds_count[$rate_interval])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "avg_over_time( scrape_duration_seconds{job=~\"$beacon_job|beacon\"} [$rate_interval])",
     "legendFormat": "prometheus_beacon_scrape_roundtrip"
    },
    {
     "expr": "avg_over_time( scrape_duration_seconds{job=~\"$validator_job|validator\"} [$rate_interval])",
     "legendFormat": "prometheus_validator_scrape_roundtrip"
    },
    {
     "expr": "rate(vc_rest_api_client_request_time_seconds_sum{routeId=\"produceAttestationData\"}[$rate_interval])\n/\nrate(vc_rest_api_client_request_time_seconds_count{routeId=\"produceAttestationData\"}[$rate_interval])",
     "legendFormat": "rest_produceAttestation_roundtrip"
    }
   ]
  },
  {
   "title": "Network status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "head slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_head_slot" }
   ]
  },
  {
   "title": "finalized epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_finalized_epoch" }
   ]
  },
  {
   "title": "previous justified epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_previous_justified_epoch"
    }
   ]
  },
  {
   "title": "current justified epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_current_justified_epoch" }
   ]
  },
  {
   "title": "current active validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_validators{status=\"active\"}"
    }
   ]
  },
  {
   "title": "validators in the activation queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_stfn_validators_in_activation_queue"
    }
   ]
  },
  {
   "title": "validators in the exit queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_stfn_validators_in_exit_queue"
    }
   ]
  },
  {
   "title": "pending deposits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_pending_deposits" }
   ]
  },
  {
   "title": "pending partial withdrawals",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_pending_partial_withdrawals"
    }
   ]
  },
  {
   "title": "pending consolidations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_pending_consolidations" }
   ]
  },
  {
   "title": "Reorgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_reorg_total[$rate_interval])"
    }
   ]
  },
  {
   "title": "Reorgs depth",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_reorg_distance_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block parent distance (except 1)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "12*rate(beacon_imported_block_parent_distance_bucket[$rate_interval])-1",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "-", "type": "text", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 } },
  {
   "title": "Node status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clock drift",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(time() - lodestar_genesis_time) / 12 - beacon_clock_slot",
     "legendFormat": "clock drift"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "lodestar_sync_status", "legendFormat": "status" }
   ]
  },
  {
   "title": "head drift",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "beacon_clock_slot - beacon_head_slot",
     "legendFormat": "clock drift"
    }
   ]
  },
  {
   "title": "-",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
   "targets": [
    { "expr": "lodestar_sync_status", "legendFormat": "status" }
   ]
  }
 ]
}