{
 "title": "Lodestar - validator monitor",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Validators connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "validator_monitor_validators" }
   ]
  },
  {
   "title": "Attestation performance summary (rate / epoch)",
   "type": "bargauge",
   "description": "https://hackmd.io/@dapplion/lodestar_attestation_summary",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "384*rate(validator_monitor_prev_epoch_attestation_summary{summary!=\"timely_head\"} [$rate_interval])",
     "legendFormat": "{{summary}}"
    }
   ]
  },
  {
   "title": "Attestation performance summary (rate / epoch)",
   "type": "timeseries",
   "description": "https://hackmd.io/@dapplion/lodestar_attestation_summary",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "384*rate(validator_monitor_prev_epoch_attestation_summary{summary!=\"timely_head\"} [$rate_interval])",
     "legendFormat": "{{summary}}"
    }
   ]
  },
  {
   "title": "Connected validators",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "1 - validator_monitor_prev_epoch_on_chain_attester_correct_head_total",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Publish Block Delay",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(validator_monitor_beacon_block_delay_seconds_bucket[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rated.network score",
   "type": "timeseries",
   "description": "Metric based on formula used by rated.network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "5/8\n*\n(\n  1 -\n  sum(rate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total[$rate_interval]))\n  /\n  sum(\n    rate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total[$rate_interval])\n    +\n    rate(validator_monitor_prev_epoch_on_chain_source_attester_hit_total[$rate_interval])\n  )\n)\n*\n(\n  (\n    1 -\n    sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total[$rate_interval]))\n    /\n    sum(\n      rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total[$rate_interval])\n      +\n      rate(validator_monitor_prev_epoch_on_chain_head_attester_hit_total[$rate_interval])\n    )\n  ) \n  + \n  (\n    1 -\n    sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total[$rate_interval]))\n    /\n    sum(\n      rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total[$rate_interval])\n      +\n      rate(validator_monitor_prev_epoch_on_chain_target_attester_hit_total[$rate_interval])\n    )\n  )\n  +\n  (\n    1\n    -\n    sum(rate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total[$rate_interval]))\n    /\n    sum(\n      rate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total[$rate_interval])\n      +\n      rate(validator_monitor_prev_epoch_on_chain_source_attester_hit_total[$rate_interval])\n    )\n  )\n) \n*\n1/3\n*\n1/(\n  sum(rate(validator_monitor_prev_epoch_on_chain_inclusion_distance_sum[$rate_interval]))\n  /\n  sum(rate(validator_monitor_prev_epoch_on_chain_inclusion_distance_count[$rate_interval]))\n)\n+\n3/8 * 1 - 0.17/100",
     "legendFormat": "Effectiveness Rating"
    }
   ]
  },
  {
   "title": "Wrong head ratio",
   "type": "timeseries",
   "description": "Percent of attestations having incorrect head.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_attester_incorrect_head_total[$rate_interval])\n/\nrate(validator_monitor_prev_epoch_on_chain_attester_hit_total[$rate_interval])",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "balance delta prev epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_balance[32m]) / validator_monitor_validators",
     "legendFormat": "balance_delta"
    }
   ]
  },
  {
   "title": "prev epoch miss ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_attester_miss_total[$rate_interval]))\n/\n(\n  sum(rate(validator_monitor_prev_epoch_on_chain_attester_hit_total[$rate_interval]))\n  +\n  sum(rate(validator_monitor_prev_epoch_on_chain_attester_miss_total[$rate_interval]))\n) > 0",
     "legendFormat": "attester"
    },
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total[$rate_interval]))\n/\n(\n  sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_hit_total[$rate_interval]))\n  +\n  sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total[$rate_interval]))\n) > 0",
     "legendFormat": "target"
    },
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total[$rate_interval]))\n/\n(\n  sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_hit_total[$rate_interval]))\n  +\n  sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total[$rate_interval]))\n) > 0",
     "legendFormat": "head"
    }
   ]
  },
  {
   "title": "Avg inclusion distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "inclusion distance"
    },
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_inclusion_distance_sum[$rate_interval])\n/\nrate(validator_monitor_prev_epoch_on_chain_inclusion_distance_count[$rate_interval])",
     "legendFormat": "inclusion distance new"
    }
   ]
  },
  {
   "title": "Inclusion distance distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "32*12*rate(validator_monitor_prev_epoch_on_chain_inclusion_distance_bucket [$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Prev epoch min delay",
   "type": "timeseries",
   "description": "Min delay from when the validator should send an object and when it was received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_attestations_min_delay_seconds_sum[$rate_interval]))\n/\nsum(rate(validator_monitor_prev_epoch_attestations_min_delay_seconds_count[$rate_interval]))",
     "legendFormat": "attestations"
    },
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_aggregates_min_delay_seconds_sum[$rate_interval]))\n/\nsum(rate(validator_monitor_prev_epoch_aggregates_min_delay_seconds_count[$rate_interval]))",
     "legendFormat": "aggregates"
    },
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_beacon_blocks_min_delay_seconds_sum[$rate_interval]))\n/\nsum(rate(validator_monitor_prev_epoch_beacon_blocks_min_delay_seconds_count[$rate_interval]))"
    }
   ]
  },
  {
   "title": "Inclusion distance distribution > 1",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "32*12*rate(validator_monitor_prev_epoch_on_chain_inclusion_distance_bucket [$rate_interval]) - 10000",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Inclusion distance distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "count(validator_monitor_prev_epoch_on_chain_inclusion_distance == 1) / count(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "1"
    },
    {
     "expr": "count(validator_monitor_prev_epoch_on_chain_inclusion_distance == 2) / count(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "2"
    },
    {
     "expr": "count(5 > validator_monitor_prev_epoch_on_chain_inclusion_distance >= 3) / count(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "3-5"
    },
    {
     "expr": "count(10 > validator_monitor_prev_epoch_on_chain_inclusion_distance >= 5) / count(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "5-10"
    },
    {
     "expr": "count(validator_monitor_prev_epoch_on_chain_inclusion_distance >= 10) / count(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "+10"
    }
   ]
  },
  {
   "title": "Attestation inclusions epoch per validator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attestation_block_inclusions_sum\n/\nvalidator_monitor_prev_epoch_attestation_block_inclusions_count",
     "legendFormat": "block_inclusions"
    },
    {
     "expr": "validator_monitor_prev_epoch_attestation_aggregate_inclusions_sum\n/\nvalidator_monitor_prev_epoch_attestation_aggregate_inclusions_count",
     "legendFormat": "aggregate_inclusions"
    }
   ]
  },
  {
   "title": "Attestater sent per epoch per validator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attestations_count / validator_monitor_validators",
     "legendFormat": "attestations_sent"
    },
    {
     "expr": "rate(validator_monitor_prev_epoch_aggregates_count[$rate_interval]) / validator_monitor_validators",
     "legendFormat": "aggregates_sent"
    }
   ]
  },
  {
   "title": "Unaggregated attestations submitted to zero peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without (le) (rate(validator_monitor_unaggregated_attestation_submitted_sent_peers_count_bucket{le=~\"0|0[.]0\"}[$rate_interval]))\n/\nrate(validator_monitor_unaggregated_attestation_submitted_sent_peers_count_count[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block proposer balance delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(validator_monitor_proposer_balance_delta_known_gwei_sum[32m])\n/\nrate(validator_monitor_proposer_balance_delta_known_gwei_count[32m])",
     "legendFormat": "known_avg"
    },
    {
     "expr": "rate(lodestar_proposer_balance_delta_any_gwei_sum[32m])\n/\nrate(lodestar_proposer_balance_delta_any_gwei_count[32m])",
     "legendFormat": "all_avg"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(lodestar_proposer_balance_delta_any_gwei_bucket[32m])) by (le))",
     "legendFormat": "all_q25"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(lodestar_proposer_balance_delta_any_gwei_bucket[32m])) by (le))",
     "legendFormat": "all_q10"
    }
   ]
  }
 ]
}