scrape_configs:
  - job_name: Lodestar
    scrape_interval: 20s
    scrape_timeout: 20s
    metrics_path: /metrics
    static_configs:
      # This tag is to be replaced in the Dockerfile with sed
      # Modified datasource to work with a network_mode: host
      - targets: ["#BEACON_URL"]
