global:
  scrape_interval: 5s
  scrape_timeout: 5s

# Tags (values starting with #) have to be replaced in the Dockerfile with sed
# Modified datasource to work with a network_mode: host
scrape_configs:
  - job_name: beacon
    metrics_path: /metrics
    static_configs:
      - targets: ["#BEACON_URL"]
  - job_name: validator
    metrics_path: /metrics
    static_configs:
      - targets: ["#VC_URL"]
