version: "3.4"
services:
  beacon_node:
    build:
      context: ../..
      dockerfile: docker/from_source.Dockerfile
    network_mode: host
    volumes:
      - .:/usr/app/amphora/v1
      - beacon_node:/data
      - logs:/logs
    command: beacon --rcConfig /usr/app/amphora/v1/rcconfig.yml --rootDir /data --logFile /logs/beacon.log
    environment:
      LODESTAR_PRESET: minimal

volumes:
  beacon_node:
  logs:
  geth:
