---

api.rest.enabled: true
api.rest.host: 0.0.0.0
api.rest.api: "*"
logFile: beacon.log
logLevelFile: debug
logRotate: true
logMaxFiles: 5
eth1.enabled: true
eth1.providerUrls: http://localhost:8545
execution.urls: http://localhost:8545
paramsFile: amphora/v1/config.yaml
genesisStateFile: amphora/v1/genesis.ssz
network.bootMultiaddrs: /ip4/35.178.114.73/tcp/9000/p2p/16Uiu2HAkz6oRBK6aKRA2uv9vxJEPhc2Rmznd5D1DqE4DoCYNqnf3
network.discv5.bootEnrs: enr:-K24QLK6c3kEq68gLIOutNuZsHKBIvR48JaAoQVrVbHK7bBJRqRX72f2feV4vEOiROQYyDNJC9z1gXeH8JsQ0U9IbTsch2F0dG5ldHOIAAAAAAAAAACEZXRoMpC_4NP0AgAAAf__________gmlkgnY0iXNlY3AyNTZrMaECRXTPHtP7GldWzvT2G_minRQbPWeGeaOW04upqcGUxeKIc3luY25ldHMAg3RjcIIjKA
