name: Build binaries

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  binaries:
    name: Build lodestar binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: amd64
          - os: warp-ubuntu-latest-arm64-4x
            platform: linux
            arch: arm64
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install arm64 specifics
        if: matrix.arch == 'arm64'
        run: |-
          # Install missing build-essential
          sudo apt-get update
          sudo apt-get install -y build-essential python3
      - uses: "./.github/actions/setup-and-build"
        with:
          node: 24
      - run: |
          mkdir -p dist
          pnpm add -g @chainsafe/caxa@3.0.6
          npx caxa -m "Unpacking Lodestar binary, please wait..." -e "dashboards/**" -e "docs/**" -D -p "pnpm clean:nm && pnpm install --frozen-lockfile --prod" --input . --output "lodestar" -- "{{caxa}}/node_modules/.bin/node" "--max-old-space-size=8192" "{{caxa}}/packages/cli/bin/lodestar.js"
          tar -czf "dist/lodestar-${{ inputs.version }}-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz" "lodestar"
      - name: Upload binaries
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: binaries-${{ matrix.os }}
          path: dist/
          if-no-files-found: error
      - name: Sanity check binary
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            exec.exec('./lodestar dev');
            await new Promise(resolve => setTimeout(resolve, 30000));
            const resp = await fetch('http://127.0.0.1:9596/eth/v1/node/version').catch(err => {
              core.setFailed(`Error accessing the API ${err}`);
              process.exit(1);
            });
            if (resp.status !== 200) {
              core.setFailed(`Failed to access API: ${resp.status}`);
              process.exit(1);
            }
            process.exit(0);
