name: Kurtosis sim tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC everyday

jobs:
  test:
    timeout-minutes: 60
    name: Build and run Kurtosis
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Build Docker image - local only
        run: >
          docker buildx build . --load \
            --tag chainsafe/lodestar:kurtosis-ci \
            --build-arg COMMIT=$(git rev-parse HEAD)
      - name: Run test
        uses: ethpandaops/kurtosis-assertoor-github-action@5932604b244dbd2ddb811516b516a9094f4d2c2f # v1
        with:
          ethereum_package_args: ".github/workflows/assets/kurtosis_sim_test_config.yaml"
