name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/labeler@v2
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
