name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        if: github.repository == 'ChainSafe/lodestar'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
