name: Release weekly (create PR only)

concurrency:
  group: cd-release-weekly

on:
  schedule:
    - cron: "23 4 * * WED"

jobs:
  prepare:
    name: Prepare Pull-Request
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=week::$(date '+%V')"
          echo "::set-output name=year::$(date '+%Y')"
      - name: Fail every other week
        run: |
          if [[ $(($WEEK%2)) -eq 0 ]]; then
            echo "Even week, skipping release..."
            exit 1
          fi
        env:
          WEEK: ${{ steps.date.outputs.week }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "lts/gallium"
          registry-url: "https://registry.npmjs.org"

      - name: Node.js version
        id: node
        run: echo "::set-output name=v8CppApiVersion::$(node --print "process.versions.modules")"
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ steps.node.outputs.v8CppApiVersion }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      - name: Bump minor version
        run: |
          node_modules/.bin/lerna version minor --yes \
          --no-git-tag-version --no-push
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --ignore-optional && yarn build
      - name: Build
        run: yarn build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      - name: Create Pull-Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: q9f <q9f@users.noreply.github.com>
          committer: q9f <q9f@users.noreply.github.com>
          branch: gacpr-release-${{ steps.date.outputs.year }}${{ steps.date.outputs.week }}
          branch-suffix: short-commit-hash
          delete-branch: true
          title: "Minor release ${{ steps.date.outputs.week }}/${{ steps.date.outputs.year }}"
          commit-message: "Minor release ${{ steps.date.outputs.week }}/${{ steps.date.outputs.year }}"
          draft: true
      - name: Check outputs
        run: |
          echo "Pull-Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull-Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
