name: Release weekly (create PR only)

concurrency:
  group: cd-release-weekly

on:
  # schedule:
  #   - cron: '23 4 * * WED'
  push:
    branches:
     - "q9-github-biweekly"

jobs:
  prepare:
    name: Prepare Pull-Request
    runs-on: ubuntu-latest
    if: ${{ W=$(date +%V); if [[ $(($W%2)) -eq 0 ]]; then echo true; else echo false; fi }}
    steps:
      - name: Check run conditions
        run: echo "test 1-2-3-4"
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     ref: master
      #     fetch-depth: 0
      # - name: Setup NodeJS
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "lts/fermium"
      #     registry-url: "https://registry.npmjs.org"
      # - name: Restore dependencies
      #   uses: actions/cache@master
      #   id: cache-deps
      #   with:
      #     path: |
      #       node_modules
      #       packages/*/node_modules
      #     key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-ignore-optional-fermium
      # - name: Bump minor version
      #   run: |
      #     node_modules/.bin/lerna version minor --yes \
      #     --no-git-tag-version --no-push
      # - name: Install & build
      #   if: steps.cache-deps.outputs.cache-hit != 'true'
      #   run: yarn install --frozen-lockfile --ignore-optional
      # - name: Build
      #   run: yarn build
      #   if: steps.cache-deps.outputs.cache-hit == 'true'
      # - name: Create Pull-Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     author: q9f <q9f@users.noreply.github.com>
      #     committer: q9f <q9f@users.noreply.github.com>
      #     branch: gacpr-release
      #     branch-suffix: short-commit-hash
      #     delete-branch: true
      #     title: "Weekly minor release"
      #     commit-message: "Weekly minor release"
      #     draft: true
      - name: Check outputs
        run: |
          echo "Pull-Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull-Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
