name: Release nightly

# only one per github sha can be run
concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "master"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.16.0"
          registry-url: "https://registry.npmjs.org"
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-ignore-optional-14.16.0
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --ignore-optional
      - name: Build
        run: yarn build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      # </common-build>
      - name: Publish to npm registry
        run: yarn run publish:nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          with_initial_version: false
        id: tag

  docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # TODO: Prevent Docker Hub tagging this image as "latest", tag as "next" instead
      - run: docker build --tag chainsafe/lodestar:${{ needs.publish.outputs.tag }} .
      - run: docker push chainsafe/lodestar:${{ needs.publish.outputs.tag }}
