name: Bun Tests
# only one can run at a time
concurrency:
  # If PR, cancel prev commits. head_ref = source branch name on pull_request, null if push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    # We intentionally don't run push on feature branches. See PR for rational.
    branches: [unstable, stable]
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests-bun:
    name: Unit Tests (Bun)
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Yarn
        run: bun install -g npm:yarn

      # This is ideal way to install with Yarn and not change the lock file
      # But it is causing the error like SSL Error: https://registry.npmjs.org/<package-name>.tgz does not support SSL
      # - name: Install
      #   run: HTTP_PROXY= HTTPS_PROXY= NO_PROXY="*" bunx --bun yarn install --ignore-engines --frozen-lockfile --registry https://registry.npmjs.org/

      - name: Install
        run: bun install --no-save || true

      - name: Build
        run: bun --bun run build

      - name: Unit Tests
        # These packages are not testable yet in Bun because of `@chainsafe/blst` dependency.
        run: excluded=(beacon-node prover light-client cli); for pkg in packages/*/; do [[ ! " ${excluded[@]} " =~ " $(basename "$pkg") " ]] && echo "Testing $(basename "$pkg")" && (cd "$pkg" && bun run --bun test:unit); done
        shell: bash
