name: Bun Tests
# only one can run at a time
concurrency:
  # If PR, cancel prev commits. head_ref = source branch name on pull_request, null if push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    # We intentionally don't run push on feature branches. See PR for rational.
    branches: [unstable, stable]
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests-bun:
    name: Unit Tests (Bun)
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # # Yarn 1 check for engine version and failed with
      # # error root@: The engine "node" is incompatible with this module. Expected version ">=22 <23". Got "24.3.0"
      # - name: Install jq
      #   uses: dcarbone/install-jq-action@v3.2.0
      # - name: Update package engine dependency
      #   run: |
      #     jq --arg version ">= $(bun -e 'console.log(process.versions.node)')" '.engines.node = $version' package.json > temp.json && mv temp.json package.json
      # - name: Detect engine version
      #   run: |
      #     jq .engines.node package.json

      - name: Install Yarn
        run: bun install -g npm:yarn
      - name: Install
        run: bunx --bun yarn install --ignore-engines --frozen-lockfile --registry https://registry.npmjs.org/
      - name: Build
        run: bunx --bun run build
      - name: Unit Tests
        # These packages are not testable yet in Bun because of `@chainsafe/blst` dependency.
        run: excluded=(beacon-node prover light-client cli); for pkg in packages/*/; do [[ ! " ${excluded[@]} " =~ " $(basename "$pkg") " ]] && echo "Testing $(basename "$pkg")" && (cd "$pkg" && bun run --bun test:unit); done
        shell: bash
